name: Deploy MultiK8s
on:
  push:
    branches:
      - main

env:
  SHA: $(git rev-parse HEAD)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Test
        run: |-
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t murilobarceloss/multi-client-test -f ./client/Dockerfile.dev ./client
          docker run -e CI=true murilobarceloss/multi-client-test npm test

      - name: Set Service Key
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'

      - name: Set Project
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: multi-435314

      - name: Auth
        run: |-
          gcloud --quiet auth configure-docker

      - name: Get Credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: multi-cluster
          location: us-central1-c

      - name: Build
        run: |-
          docker build -t murilobarceloss/multi-client-k8s:latest -t murilobarceloss/multi-client-k8s:${{ env.SHA }} -f ./client/Dockerfile ./client
          docker build -t murilobarceloss/multi-server-k8s:latest -t murilobarceloss/multi-server-k8s:${{ env.SHA }} -f ./server/Dockerfile ./server
          docker build -t murilobarceloss/multi-worker-k8s:latest -t murilobarceloss/multi-worker-k8s:${{ env.SHA }} -f ./worker/Dockerfile ./worker

      - name: Push
        run: |-
          docker push murilobarceloss/multi-client-k8s:latest
          docker push murilobarceloss/multi-server-k8s:latest
          docker push murilobarceloss/multi-worker-k8s:latest
          
          docker push murilobarceloss/multi-client-k8s:${{ env.SHA }}
          docker push murilobarceloss/multi-server-k8s:${{ env.SHA }}
          docker push murilobarceloss/multi-worker-k8s:${{ env.SHA }}

      - name: Apply
        run: |-
          kubectl apply -f k8s
          kubectl set image deployments/server-deployment server=murilobarceloss/multi-server-k8s:${{ env.SHA }}
          kubectl set image deployments/client-deployment client=murilobarceloss/multi-client-k8s:${{ env.SHA }}
          kubectl set image deployments/worker-deployment worker=murilobarceloss/multi-worker-k8s:${{ env.SHA }}
